# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1335, 987)
        self.beam_io = QtWidgets.QSpinBox(Dialog)
        self.beam_io.setGeometry(QtCore.QRect(300, 190, 47, 24))
        self.beam_io.setObjectName("beam_io")
        self.gain_io = QtWidgets.QLineEdit(Dialog)
        self.gain_io.setGeometry(QtCore.QRect(220, 220, 113, 23))
        self.gain_io.setObjectName("gain_io")
        self.phi_io = QtWidgets.QDoubleSpinBox(Dialog)
        self.phi_io.setGeometry(QtCore.QRect(280, 250, 66, 24))
        self.phi_io.setMinimum(-100.0)
        self.phi_io.setMaximum(360.0)
        self.phi_io.setObjectName("phi_io")
        self.theta_io = QtWidgets.QDoubleSpinBox(Dialog)
        self.theta_io.setGeometry(QtCore.QRect(280, 280, 66, 24))
        self.theta_io.setMinimum(-100.0)
        self.theta_io.setMaximum(360.0)
        self.theta_io.setObjectName("theta_io")
        self.save_audio_button = QtWidgets.QPushButton(Dialog)
        self.save_audio_button.setGeometry(QtCore.QRect(160, 340, 101, 23))
        self.save_audio_button.setObjectName("save_audio_button")
        self.reset_values = QtWidgets.QPushButton(Dialog)
        self.reset_values.setGeometry(QtCore.QRect(100, 310, 101, 23))
        self.reset_values.setObjectName("reset_values")
        self.update_values = QtWidgets.QPushButton(Dialog)
        self.update_values.setGeometry(QtCore.QRect(230, 310, 101, 23))
        self.update_values.setObjectName("update_values")
        self.bfc = QtWidgets.QLabel(Dialog)
        self.bfc.setGeometry(QtCore.QRect(120, 140, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bfc.setFont(font)
        self.bfc.setObjectName("bfc")
        self.garph_headline = QtWidgets.QLabel(Dialog)
        self.garph_headline.setGeometry(QtCore.QRect(750, 100, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.garph_headline.setFont(font)
        self.garph_headline.setObjectName("garph_headline")
        self.beam_label = QtWidgets.QLabel(Dialog)
        self.beam_label.setGeometry(QtCore.QRect(100, 190, 91, 21))
        self.beam_label.setObjectName("beam_label")
        self.gain_label = QtWidgets.QLabel(Dialog)
        self.gain_label.setGeometry(QtCore.QRect(100, 220, 91, 21))
        self.gain_label.setObjectName("gain_label")
        self.phi_label = QtWidgets.QLabel(Dialog)
        self.phi_label.setGeometry(QtCore.QRect(100, 250, 91, 21))
        self.phi_label.setObjectName("phi_label")
        self.theta_label = QtWidgets.QLabel(Dialog)
        self.theta_label.setGeometry(QtCore.QRect(100, 280, 91, 21))
        self.theta_label.setObjectName("theta_label")
        self.terminate = QtWidgets.QPushButton(Dialog)
        self.terminate.setGeometry(QtCore.QRect(1200, 950, 111, 23))
        self.terminate.setObjectName("terminate")
        self.stream_beam_2 = QtWidgets.QPushButton(Dialog)
        self.stream_beam_2.setGeometry(QtCore.QRect(130, 780, 41, 23))
        self.stream_beam_2.setObjectName("stream_beam_2")
        self.stream_beam_3 = QtWidgets.QPushButton(Dialog)
        self.stream_beam_3.setGeometry(QtCore.QRect(180, 780, 41, 23))
        self.stream_beam_3.setObjectName("stream_beam_3")
        self.stream_beam_4 = QtWidgets.QPushButton(Dialog)
        self.stream_beam_4.setGeometry(QtCore.QRect(230, 780, 41, 23))
        self.stream_beam_4.setObjectName("stream_beam_4")
        self.stream_beam_5 = QtWidgets.QPushButton(Dialog)
        self.stream_beam_5.setGeometry(QtCore.QRect(280, 780, 41, 23))
        self.stream_beam_5.setObjectName("stream_beam_5")
        self.stream_beam_6 = QtWidgets.QPushButton(Dialog)
        self.stream_beam_6.setGeometry(QtCore.QRect(280, 750, 41, 23))
        self.stream_beam_6.setObjectName("stream_beam_6")
        self.stream_beam_7 = QtWidgets.QPushButton(Dialog)
        self.stream_beam_7.setGeometry(QtCore.QRect(230, 750, 41, 23))
        self.stream_beam_7.setObjectName("stream_beam_7")
        self.stream_beam_8 = QtWidgets.QPushButton(Dialog)
        self.stream_beam_8.setGeometry(QtCore.QRect(180, 750, 41, 23))
        self.stream_beam_8.setObjectName("stream_beam_8")
        self.stream_beam_9 = QtWidgets.QPushButton(Dialog)
        self.stream_beam_9.setGeometry(QtCore.QRect(130, 750, 41, 23))
        self.stream_beam_9.setObjectName("stream_beam_9")
        self.garph_headline_3 = QtWidgets.QLabel(Dialog)
        self.garph_headline_3.setGeometry(QtCore.QRect(130, 490, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.garph_headline_3.setFont(font)
        self.garph_headline_3.setObjectName("garph_headline_3")
        self.BeamsW = QtWidgets.QWidget(Dialog)
        self.BeamsW.setGeometry(QtCore.QRect(20, 520, 411, 211))
        self.BeamsW.setObjectName("BeamsW")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(450, 130, 811, 711))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.save_audio_button.setText(_translate("Dialog", "Save Audio"))
        self.reset_values.setText(_translate("Dialog", "Load Values"))
        self.update_values.setText(_translate("Dialog", "Update Values"))
        self.bfc.setText(_translate("Dialog", "Beam Former Control"))
        self.garph_headline.setText(_translate("Dialog", "Omni Mic Array Latest Doa\'s"))
        self.beam_label.setText(_translate("Dialog", "Beam"))
        self.gain_label.setText(_translate("Dialog", "Gain"))
        self.phi_label.setText(_translate("Dialog", "Phi"))
        self.theta_label.setText(_translate("Dialog", "Theta"))
        self.terminate.setText(_translate("Dialog", "Safe Terminate"))
        self.stream_beam_2.setText(_translate("Dialog", "0"))
        self.stream_beam_3.setText(_translate("Dialog", "1"))
        self.stream_beam_4.setText(_translate("Dialog", "2"))
        self.stream_beam_5.setText(_translate("Dialog", "3"))
        self.stream_beam_6.setText(_translate("Dialog", "4"))
        self.stream_beam_7.setText(_translate("Dialog", "5"))
        self.stream_beam_8.setText(_translate("Dialog", "6"))
        self.stream_beam_9.setText(_translate("Dialog", "7"))
        self.garph_headline_3.setText(_translate("Dialog", "Beams Amplitude (BF)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Omni Mic Array Latest Doa\'s"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Omni Mic Array Latest Classifications"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

