# coding: utf-8

"""
    Insight Sentinel API

    API to control beamforming on a Insight Sentinel device  # noqa: E501

    OpenAPI spec version: 0.0.0
    Contact: jonathan@insightacoustics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Gps(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'latitude': 'float',
        'longitude': 'float',
        'elevation': 'float',
        'locked': 'bool'
    }

    attribute_map = {
        'latitude': 'latitude',
        'longitude': 'longitude',
        'elevation': 'elevation',
        'locked': 'locked'
    }

    def __init__(self, latitude=None, longitude=None, elevation=None, locked=None):  # noqa: E501
        """Gps - a model defined in Swagger"""  # noqa: E501

        self._latitude = None
        self._longitude = None
        self._elevation = None
        self._locked = None
        self.discriminator = None

        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude
        if elevation is not None:
            self.elevation = elevation
        if locked is not None:
            self.locked = locked

    @property
    def latitude(self):
        """Gets the latitude of this Gps.  # noqa: E501


        :return: The latitude of this Gps.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this Gps.


        :param latitude: The latitude of this Gps.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this Gps.  # noqa: E501


        :return: The longitude of this Gps.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this Gps.


        :param longitude: The longitude of this Gps.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    @property
    def elevation(self):
        """Gets the elevation of this Gps.  # noqa: E501


        :return: The elevation of this Gps.  # noqa: E501
        :rtype: float
        """
        return self._elevation

    @elevation.setter
    def elevation(self, elevation):
        """Sets the elevation of this Gps.


        :param elevation: The elevation of this Gps.  # noqa: E501
        :type: float
        """

        self._elevation = elevation

    @property
    def locked(self):
        """Gets the locked of this Gps.  # noqa: E501


        :return: The locked of this Gps.  # noqa: E501
        :rtype: bool
        """
        return self._locked

    @locked.setter
    def locked(self, locked):
        """Sets the locked of this Gps.


        :param locked: The locked of this Gps.  # noqa: E501
        :type: bool
        """

        self._locked = locked

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Gps, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Gps):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
